spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/coba
    username: postgres
    password: postgres
    pool:
      max-size: 20
      initial-size: 10
      enabled: true
  redis:
    host: localhost
    database: 0
    password: redis
server:
  port: